# Generated by Django 3.0.2 on 2020-02-01 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
        ('evaluations', '0001_initial'),
        ('core', '0003_touristspot_attractions'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristspot',
            name='comments',
            field=models.ManyToManyField(to='comments.Comment'),
        ),
        migrations.AddField(
            model_name='touristspot',
            name='evaluations',
            field=models.ManyToManyField(to='evaluations.Evaluation'),
        ),
    ]
