# Generated by Django 3.0.2 on 2020-02-01 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
        ('core', '0004_auto_20200201_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristspot',
            name='address',
            field=models.ManyToManyField(to='address.Address'),
        ),
    ]
