# Generated by Django 3.0.2 on 2020-02-01 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
        ('core', '0005_touristspot_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='touristspot',
            name='address',
        ),
        migrations.AddField(
            model_name='touristspot',
            name='address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='address.Address'),
            preserve_default=False,
        ),
    ]
