# Generated by Django 3.0.2 on 2020-02-01 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line1', models.CharField(max_length=155)),
                ('line2', models.CharField(blank=True, max_length=155, null=True)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('lat', models.IntegerField(blank=True, null=True)),
                ('long', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
